# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instruction.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_i(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 650)
        MainWindow.setMinimumSize(QtCore.QSize(480, 650))
        MainWindow.setMaximumSize(QtCore.QSize(480, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(52, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(13, 56, 452, 572))
        self.plainTextEdit.setMinimumSize(QtCore.QSize(452, 572))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(452, 572))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Инструкция"))
        self.label.setText(_translate("MainWindow", "Инструкция по работе с приложением"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "1) Подготовка к работе\n"
"    1.1) В приложении предоставлены два раздела: «Разметка объектов», «Разметка дефектов». В которых осуществляется работа с магнитограммами.\n"
"    1.2) Для того чтобы начать размечать магнитограмму нужно выбрать изображение, с которым вы будете работать. Для этого нажмите на кнопку \"выбрать файл\" и выберите файл с магнитограммой.\n"
"2) Работа с разметкой магнитограмм\n"
"    2.1) После появления не размеченной магнитограммы, вы можете приступить к разметке. В разделе \"разметка объектов\" выберите тип элемента и нанесите его на поле разметки. В разделе \"разметка дефектов\" отметьте дефекты на поле разметки. ВАЖНО: выделяйте объекты прямоугольниками от верхнего до нижнего края.\n"
"    2.2) В случае неверного выделения в поле для внесения разметки нажмите на кнопку \"очистить поле для объектов\" или \"очистить поле для дефектов\" соответственно.\n"
"    2.3) Если возникнут трудности с разметкой или нужно будет проверить свою работу, вы можете воспользоваться функцией \"Получить ответ от нейронной сети\", ответ появиться в отдельном окне.\n"
"    2.3.1) В окне появится разметка сделанная вами и разметка, которую выполнила нейронная сеть. Вы сможете рассмотреть различия в разметке магнитограммы и узнать точность разметки (в процентах) вашей работы и точность разметки (в процентах) нейронной сети, а также общую точность на объектах и дефектах (в процентах).\n"
"    2.4) После завершения работы нажмите кнопку \"Сохранить изображения\"(Для раздела «Разметка новых магнитограмм»).\n"
""))
        self.plainTextEdit.setReadOnly(True)
